### ISSUE TITLE
timeseries script

### ISSUE THREAD

**Issue by dabail10** [NCAR/CESM_postprocessing#1]
This script still lists caseroot as the "postprocess" directory and should be one level up. Also, the code does not work with gzipped files, but does not print a message to this effect.

**Comment by bertinia** [comment]
The issue with the "postprocess" directory and stand-alone caseroot has been fixed. The cesm_tseries_generator.py script also prints a warning if the input history file doesn't end with
the .nc extension. 

The trunk tag of the postprocessing tools at URL:
https://svn-ccsm-models.cgd.ucar.edu/postprocessing/trunk_tags/postprocessing_20160426a
