### ISSUE TITLE
missing ice diag set 4 plots

### ISSUE THREAD

**Issue by jtruesdal** [NCAR/CESM_postprocessing#13]
I'm not getting all of my ice diagnostic plots for set 4 and am getting the following errors in the log.  This used to work for me.  Not sure if this is related to issue #11.

Here is a web page showing the problem:
http://webext.cgd.ucar.edu//B1850/ocn-dev/b.e15.B1850_WW3.f09_g16.lang_redi_2hr.001/ice/proc/diag/b.e15.B1850_WW3.f09_g16.lang_redi_2hr.001/b.e15.B1850_WW3.f09_g16.lang_redi_2hr.001-b.e15.B1850.f09_g16.pi_control.36/yrs36-55/index.html

NOT FOUND: /glade/scratch/jet/archive/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001/ice/proc/diag/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001
//g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001-g.e15.GIAF.T62_gx1v6.e15_ctrl.002//yrs146-165//contour/diff_con_jfm_albsni_cice_NH.png
NOT FOUND: /glade/scratch/jet/archive/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001/ice/proc/diag/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001//g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001-g.e15.GIAF.T62_gx1v6.e15_ctrl.002//yrs146-165//contour/diff_con_amj_albsni_cice_NH.png
NOT FOUND: /glade/scratch/jet/archive/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001/ice/proc/diag/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001//g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001-g.e15.GIAF.T62_gx1v6.e15_ctrl.002//yrs146-165//contour/diff_con_jas_albsni_cice_NH.png
NOT FOUND: /glade/scratch/jet/archive/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001/ice/proc/diag/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001//g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001-g.e15.GIAF.T62_gx1v6.e15_ctrl.002//yrs146-165//contour/diff_con_ond_albsni_cice_NH.png
NOT FOUND: /glade/scratch/jet/archive/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001/ice/proc/diag/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001//g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001-g.e15.GIAF.T62_gx1v6.e15_ctrl.002//yrs146-165//contour/diff_con_ann_albsni_cice_NH.png
NOT FOUND: /glade/scratch/jet/archive/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001/ice/proc/diag/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001//g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001-g.e15.GIAF.T62_gx1v6.e15_ctrl.002//yrs146-165//contour/diff_con_jfm_albsni_cice_SH.png
NOT FOUND: /glade/scratch/jet/archive/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001/ice/proc/diag/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001//g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001-g.e15.GIAF.T62_gx1v6.e15_ctrl.002//yrs146-165//contour/diff_con_amj_albsni_cice_SH.png
NOT FOUND: /glade/scratch/jet/archive/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001/ice/proc/diag/g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001//g.e15.GIAF_WAV.T62_gx1v6_rx1_ww3a.lang_redi_2hr.001-g.e15.GIAF.T62_gx1v6.e15_ctrl.002//yrs146-165//contour/diff_con_jas_albsni_cice_SH.png

**Comment by bertinia** [comment]
Fixed with postprocessing SVN trunk tag:
https://svn-ccsm-models.cgd.ucar.edu/postprocessing/trunk_tags/postprocessing_20160502

This tag includes an updated version of pyAverager in the SVN_EXTERNALS_DIRECTORY so be sure the new version is included if you run "svn up" in your existing postprocessing sandbox.

After updated your sandbox, be sure to run the following commands:
>cd $postprocessing
>make clobber
>make clobber-env
>./create_python_env -cimeroot $CIMEROOT -machine yellowstone

Your existing postprocessing caseroots should be fine and can run with this updated postprocessing sandbox.
