### ISSUE TITLE
problems atm diags cam-chem NCL script profiles_aircraft_noaa.ncl

### ISSUE THREAD

**Issue by bertinia** [NCAR/CESM_postprocessing#151]
The current profiles_aircraft_noaa.ncl references variables in obs data files that
don't exist. The NCL script needs to be updated to match the current obs files
that reside in:

/glade/p/cesm/amwg/amwg_data/obs_data/cam-chem

Unless there is another obs data set that we should point to in the env_diags_atm.xml setting?

Here are the errors:

(0)     rin1 = $OBS_DATA/cam-chem/TexAQS2000_o3_Texas.nc
fatal:["Execute.c":6397]:variable (prof_med) is not in file (rin1)
^Mfatal:["Execute.c":8640]:Execute: Error occurred at or near line 224 in file /glade/p/work/aliceb/sandboxes/dev/postprocessing_ch/atm_diag/profiles_aircraft_noaa.ncl

It tries to read the following variables:

    air1_med = rin1->prof_med
    air1_p25 = rin1->prof_p25
    air1_p75 = rin1->prof_p75

but they don't exist in the file. However, vars dmed, d25pt and d75pt do exist - should these variables be used instead?

**Comment by tilmes** [comment]
Yes, it should be dmed, d25pt and d75pt.

**Comment by tilmes** [comment]
I have modified the code, please try:
/glade/p/acd/tilmes/amwg/amwg_diagnostics_dev/code/profiles_aircraft_noaa.ncl

**Comment by bertinia** [comment]
fixed with PR #147.
