### ISSUE TITLE
create_python_env not working

### ISSUE THREAD

**Issue by alperaltuntas** [NCAR/CESM_postprocessing#160]
An error is triggered when running create_python_env both on stampede2 and on cheyenne. Particularly, the error is encountered when cf_units/2.0.2 is attempted to be installed.

The error message is as follows:

     Running cf-units-2.0.2/setup.py -q bdist_egg --dist-dir /glade/scratch/altuntas/easy_install- 
     PQSxZd/cf-units-2.0.2/egg-dist-tmp-vAnLBe
     warning: no previously-included files found matching 'cf_units/etc/site.cfg'
     UPDATING build/lib.linux-x86_64-2.7/cf_units/_version.py
     set build/lib.linux-x86_64-2.7/cf_units/_version.py to '2.0.2'
     cf_units/_udunits2.c(553): catastrophic error: cannot open source file "udunits2.h"
       #include "udunits2.h"
                       ^

     compilation aborted for cf_units/_udunits2.c (code 4)
     error: Setup script exited with error: command 'icc' failed with exit status 4

I did the following two and create_python_env appears to work fine now:

1. remove ```ilamb``` from SUBDIRS in Makefile (line 30)
2. remove ```ilamb>=2.1``` from diagnostics/requirements.txt (line 3)

Not sure what the complications are (other than the absence of ILAMB).

(My local copy: /glade/p/work/altuntas/cesm.diags/CESM_postprocessing_test )

**Comment by bertinia** [comment]
@alperaltuntas - thanks for entering the issue. I'm testing IOMB on a new instance of the NPL on
the DAV with cf_units v2.0.2 installed. IOMB uses the ILAMB framework and NPL is the new
NCAR python virtualenv that Brian Vanderwende has built with python2.7.14 to replace the
module dependency management. The workaround that you found is fine and should only
affect ILAMB and IOMB.
