### ISSUE TITLE
extra data error

### ISSUE THREAD

**Issue by lvankampenhout** [NCAR/CESM_postprocessing#184]
I ran `timeseries`twice in a row. This generated a `ts_status.log` with two lines in it, see attachment. 

The next time that I run `timeseries` I get this error: 
```
ValueError: Extra data: line 2 column 1 - line 2 column 401121 (char 385576 - 786696)
Traceback (most recent call last):
  File "/nfs/home1/kampe004/github/CESM_postprocessing/timeseries/timeseries/cesm_tseries_generator.py", line 411, in <module>
(...)
  File "/nfs/home1/kampe004/github/CESM_postprocessing/timeseries/timeseries/chunking.py", line 362, in read_log
    d = json.load(f)
```
[ts_status.log](https://github.com/NCAR/CESM_postprocessing/files/2603821/ts_status.log)

**Comment by bertinia** [comment]
I'm not sure what you're data input files looked like but there's an issue with the cam.h2 history stream in that it's entered twice in the ts_status.log. (open the ts_status.log file and search for "index" to see all the streams that were converted to single variable timeseries).   I would try deleting the existing single variable timeseries files and the ts_status.log file and resubmit.

**Comment by lvankampenhout** [comment]
I deleted one of the (identical) double entries and then it worked again. Thanks.
