### ISSUE TITLE
Latest tag postprocessing_20160609

### ISSUE THREAD

**Issue by dabail10** [NCAR/CESM_postprocessing#21]
I get the following error when trying to create a postprocess with the latest tag. Everything works fine with the postprocessing_20160523 tag.

./create_postprocess -backtrace -debug 3 -caseroot /glade/scratch/dbailey/b.e15.B1850.f09_g16.pi_control.all.62b 
'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "./create_postprocess", line 605, in <module>
    status = main(options)
  File "./create_postprocess", line 499, in main
    envDict = initialize_main(envDict, options, standalone)
  File "./create_postprocess", line 456, in initialize_main
    if options.cesmtag[0]:
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by bertinia** [comment]
In the latest tag, postprocessing_20160609, I added an optional argument to create_postprocess
to identify the cesm tag used to produce the data. The new option is documented in the
create_postprocess --help and is specified by --cesmtag [tagname]. I had a logic bug
in the option parsing that has been fixed on the trunk and with the latest trunk tag:

https://svn-ccsm-models.cgd.ucar.edu/postprocessing/trunk_tags/postprocessing_20160615/
