### ISSUE TITLE
Use xmlquery with postprocessing env files

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/CESM_postprocessing#219]
It would be really nice to be able to use `xmlquery` (and `xmlchange`) with the xml files in `postprocessing/`. I've tried two different ways, and they fail with different errors:

```
$ ./xmlquery --file postprocess/env_postprocess.xml TIMESERIES_INPUT_ROOTDIR
setting case file to postprocess/env_postprocess.xml
ERROR: No match found for file type config_definition
$ cd postprocess/
$ ../xmlquery --file env_postprocess.xml TIMESERIES_INPUT_ROOTDIR
ERROR: Makes no sense to have empty read-only file
```

**Comment by bertinia** [comment]
@mnlevy1981 - Does pp_config support what you need?

**Comment by mnlevy1981** [comment]
@bertinia -- it does, thanks! (@sherimickelson pointed this out in the CSEG meeting, and I updated a related issue but forgot to come back and close this one)
