### ISSUE TITLE
env_diags_ice.xml DIAGOBSROOT

### ISSUE THREAD

**Issue by dabail10** [NCAR/CESM_postprocessing#22]
Looks like some scripts expect this to be /glade/p/cesm/pcwg while others expect it to be /glade/p/cesm/pcwg/ice/data. These need to be consistent. I would prefer the former.

Dave

**Comment by bertinia** [comment]
Can you list which scripts are affected? I ran into a similar problem and was able to successfully
generate plots with the following env_diags_ice.xml settings:

env_diags_ice.xml:<entry id="ICEDIAG_DIAGOBSROOT" value="/glade/p/cesm/pcwg/ice/data/" />

env_diags_ice.xml:<entry id="ICEDIAG_SSMI_PATH" value="$ICEDIAG_DIAGOBSROOT/SSMI.ifrac.1979-2000monthlymean.gx1v5.nc" />

env_diags_ice.xml:<entry id="ICEDIAG_ASPeCt_PATH" value="$ICEDIAG_DIAGOBSROOT/ASPeCt_monthly_1x1.nc" />

env_diags_ice.xml:<entry id="ICEDIAG_REGION_MASK_FILE" value="$ICEDIAG_DIAGOBSROOT/REGION_MASK.nc" />

**Comment by dabail10** [comment]
I might have an issue with the tag version. I am looking into it.

**Comment by dabail10** [comment]
Ok. I think I have it figure out. The variable DIAGOBSROOT is set to /glade/p/cesm/pcwg. Then later in env_diags_ice.xml, for ICEDIAG_SSMI_PATH, ICEDIAG_ASPeCt_PATH, and ICEDIAG_REGION_MASK_FILE concatenate the 'ice/data'. However, the NCL scripts use DIAGOBSROOT and do not concatenate 'ice/data'. So, I think the only change is to edit the 'ICEDIAG' variables so that 'ice/data' is not added and instead DIAGOBSROOT includes 'ice/data'. Does that make sense?

**Comment by bertinia** [comment]
Yes, that's correct and this change is included in the latest
postprocessing tag.

On Thu, Jun 16, 2016 at 11:06 AM, dabail10 <notifications@github.com> wrote:

> Ok. I think I have it figure out. The variable DIAGOBSROOT is set to
> /glade/p/cesm/pcwg. Then later in env_diags_ice.xml, for ICEDIAG_SSMI_PATH,
> ICEDIAG_ASPeCt_PATH, and ICEDIAG_REGION_MASK_FILE concatenate the
> 'ice/data'. However, the NCL scripts use DIAGOBSROOT and do not concatenate
> 'ice/data'. So, I think the only change is to edit the 'ICEDIAG' variables
> so that 'ice/data' is not added and instead DIAGOBSROOT includes
> 'ice/data'. Does that make sense?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/NCAR/CESM_postprocessing/issues/22#issuecomment-226549512>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKO3mV0Albc9ysSqKkeDS3iMT_6A1kczks5qMYKcgaJpZM4I22Ew>
> .
>



-- 
Alice Bertini
NCAR - CSEG Software Engineer
