### ISSUE TITLE
Yrs averaged in land diagnostics plot titles are trends, not climos

### ISSUE THREAD

**Issue by olyson** [NCAR/CESM_postprocessing#23]
The climatology years that are shown in the land diagnostics plot titles, e.g., set_2, are showing trends years, not the climatology years.  The climatology years for the plot titles are taken from the global attribute "yrs_averaged" in the climatology netcdf files, which have trend years, not climo years.  I imagine this is being done somewhere in the python averager scripts.

**Comment by bertinia** [comment]
Fixed with pyAverager v0.9.8. This code was tested and checked into the trunk and tagged at:https://svn-ccsm-models.cgd.ucar.edu/postprocessing/trunk_tags/postprocessing_20160715/
