### ISSUE TITLE
create a common location for the virtualenv on yellowstone

### ISSUE THREAD

**Issue by bertinia** [NCAR/CESM_postprocessing#27]
Need to install the postprocessing virtualenv in a common location on yellowstone so users only need to cd to that dir and run create_postprocess for their particular case. This will also allow updates to the postprocessing code without requiring early adopters to update and run create_python_env.

**Comment by gold2718** [comment]
I'm not sure what the virtualenv is but can't users just run a script from wherever they are by specifying the path to the script or putting that location in their PATH? Scripts that only run from a special directory can be fragile.

**Comment by bertinia** [comment]
So, there's a bootstrapping chicken and egg problem here. 

You need to have your path and pythonpath set correctly to find all the postprocessing modules. There's 2 ways to do this:
1. cd into the common location for postprocessing and create_postprocess will set everything for you that it needs to know via relative paths (similar to CIME)
or
2. activate the virtualenv which will setup all the paths correctly and then you can run create_postprocess from any location. 

Since there's always one step that needs to be done to bootstrap, which one do we want?

**Comment by gold2718** [comment]
For #1, a script knows where it is located and can cd to its own directory to create or work with relative paths so it seems to me that the user should not have to do the cd themselves.

However, wouldn't the Yellowstone way to do this be to have CISL set up a module for post processing?
module load cesm_pp or
module load cesm_post_processing

this is similar (or identical?) to your #2.

**Comment by bertinia** [comment]
Yes, the plan is to ultimately have CISL create a module for CESM postprocessing. I'm still doing
some development and testing so didn't want to have to ask them to create a new module version
every time I updated the code.

**Comment by gold2718** [comment]
Then it seems that writing a script to mimic the module loader (#2) would be best.
If it would help, I have a script that adds something to your path if it is not already there.
See /glade/u/home/goldy/bin/addPath.sh

**Comment by bertinia** [comment]
Done. See the wiki Yellowstone Quick Start Guide for details on how to setup.
