### ISSUE TITLE
model vs model ice/lnd timeseries files in correct dirs

### ISSUE THREAD

**Issue by shieldsca** [NCAR/CESM_postprocessing#39]
1.  model ice diags:   need to copy ice_vol_\* (timeseries) file for the "Control" (which is the main case, it is not the "Diff" case) over to the model_vs_model subdirectory from the main climo directory
2. same for land, case 2 file needs to be in the model_vs_model dir:   *ANN_ALL.nc file

**Comment by bertinia** [comment]
Is there a test case where this failed for the lnd diags? I suspect there may be a problem when
the casename has a "-" in it and the python pattern match used to create the symbolic links.

Item 1. above is fixed with PR #47.

**Comment by bertinia** [comment]
FIxed with PR #51. Please check the examples/CESM2.0-PI-Control xml file settings to see examples of path settings that produce expected results.
