### ISSUE TITLE
omwg obs_data files need to be generated for gx1v7 grid

### ISSUE THREAD

**Issue by bertinia** [NCAR/CESM_postprocessing#91]
There are a number of missing ocn diag obs files that haven't been created for the
gx1v7 grid. This includes, but may not be limited to, the following:

/glade/p/cesm/omwg/obs_data/ssh/1992-2002MDOT060401.gx1v7.nc

@alperaltuntas is going to look into creating these files along with the
hi-res (0.1 degree), 42 level files that still need to be created. 

We may also need to make some changes to the underlying NCL scripts.

**Comment by alperaltuntas** [comment]
Update:
I've created the following missing gx1v7 diag obs files:
- /glade/p/cesm/omwg/obs_data/ssh/1992-2002MDOT060401.gx1v7.nc
- /glade/p/cesm/omwg/obs_data/phc/POP_format/PHC2_SALT_gx1v7_ann_avg.nc
- /glade/p/cesm/omwg/obs_data/phc/POP_format/PHC2_TEMP_gx1v7_ann_avg.nc
- /glade/p/cesm/omwg/obs_data/phc/PHC2_RHO0_gx1v7.nc

Will also look into creating 42 level files.

**Comment by bertinia** [comment]
Thanks @alperaltuntas! - did you get a chance to test run the diags with these
updated files?

**Comment by alperaltuntas** [comment]
Alice,

Sorry, I just had a chance to test the diags with these updated files. They seem to be working fine. Examples: 
- http://webext.cgd.ucar.edu/B1850/b.e20.B1850.f09_g17.pi_control.all.190/ocn/index.20170731-113245.html
-http://webext.cgd.ucar.edu/B1850/b.e20.B1850.f09_g17.pi_control.all.191/ocn/index.20170731-114602.html
-http://webext.cgd.ucar.edu/B20TH/b.e20.BHIST.f09_g17.20thC.190_01-ocn/ocn/

By the way, I don't seem to have permissions to write to `B20TH/b.e20.BHIST.f09_g17.20thC.190_01/`, so I saved ocn files to `B20TH/b.e20.BHIST.f09_g17.20thC.190_01-ocn/`. I am included in ccsmdiag group, so I shouldn't have this permission issue. Any idea about why?

**Comment by bertinia** [comment]
Yes, it looks like @cecilehannay  removed group write permissions:

In /project/diagnostics/external/B20TH:
drwxr-sr-x  3 hannay   ccsmdiag      4096 Jul 31 11:49 b.e20.BHIST.f09_g17.20thC.190_01/
drwxr-sr-x  3 altuntas ccsmdiag      4096 Jul 31 12:50 b.e20.BHIST.f09_g17.20thC.190_01-ocn/

Looks like we're still missing the 2-D global zonal averaged surface heat flux (SHF) and salt flux (SFWF) in the model vs. obs plots but I think that's because either the obs data or the model data is missing these fields?

**Comment by alperaltuntas** [comment]
I believe it is the model data that is missing for those two fields. (See logs files in /glade/p/work/altuntas/cesm.diags/ ):
...
(0)     SHF_TOTAL is not in file.
...
(0)     SFWF_TOTAL is not in file.

Also, it looks like these fields were missing in the diagnostics of runs with gx1v6 as well. An example: http://webext.cgd.ucar.edu/B1850/b.e20.B1850.f09_g16.pi_control.all.142/ocn/diag_work.22-41/MODEL_VS_OBS/

**Comment by bertinia** [comment]
@alperaltuntas is going to talk with @klindsay28 to find out why the surface flux zonal average
plots aren't correctly including the observations. Also, looks like variables SHF_TOTAL was 
renamed to SHF and SFWF_TOTAL to SFWF in POP sometime between CESM1.5 and
CESM2.0 tuning runs. These variable name changes require some modifications to the NCL routines
sfcflx_za.ncl and sfcflx_za_diff.ncl as well as updates to support gx1v7 resolution logic.

**Comment by bertinia** [comment]
@phillips-ad found a bug in NCL6.4.0 related to the setting of plot resource:
res@gsnYRefLine = 0.0
in both the sfcflx.ncl and sfcflx_za.ncl scripts.  Commenting out this line for now. 

In addition, there are some logic errors related to the support for the gx1v7 grid and the 
variable field name changes in pop monthly history files with newer versions of CESM2:
SHF_TOTAL is now just SHF
SFWF_TOTAL is now just SFWF
The generated HTML allows for both variable plots in order to support data generated
with older versions of CESM1.
